service: seek-graphql

provider:
  name: aws
  runtime: go1.x
  stage: dev
  profile: serverless-admin
  region: eu-central-1

package:
 exclude:
   - ./**
 include:
   - ./bin/sls-api-gateway

custom:
  vars:
    corsAllowOrigin: "www.example.com"
    corsAllowMethods: "OPTIONS,POST"

functions:
  seek-graphql:
    handler: bin/sls-api-gateway
    environment:
      CORS_ALLOW_ORIGIN: ${self:custom.vars.corsAllowOrigin}
      CORS_ALLOW_METHODS: ${self:custom.vars.corsAllowMethods}
    events:
      - http:
          path: seek-graphql
          method: post
          cors:
            origin: ${self:custom.vars.corsAllowOrigin}
