service: seek-graphql

provider:
  name: aws
  stage: dev
  profile: serverless-admin
  region: eu-central-1

package:
  individually: true

custom:
  vars:
    corsAllowOrigin: "www.example.com"
    corsAllowMethods: "OPTIONS,POST"

functions:
  seek-graphql:
    runtime: go1.x
    package:
      exclude:
        - ./**
      include:
        - ./bin/sls-api-gateway
    handler: bin/sls-api-gateway
    environment:
      CORS_ALLOW_ORIGIN: ${self:custom.vars.corsAllowOrigin}
      CORS_ALLOW_METHODS: ${self:custom.vars.corsAllowMethods}
    events:
      - http:
          path: seek-graphql
          method: post
          cors:
            origin: ${self:custom.vars.corsAllowOrigin}
#          authorizer: authorizer-func-auth0
  authorizer-func-auth0:
    runtime: nodejs6.10
    package:
      include:
        - ./auth0-authorizer/*
    handler: auth0-authorizer/auth.authorize
